name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]        # main 分支推送触发 latest
    tags:
      - "v*"                    # 推送 v* tag 触发版本号镜像
  workflow_dispatch:            # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 设置 buildx + QEMU
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # 3️⃣ 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ 构建并推送多架构镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            jin00000/myapp:latest
            jin00000/myapp:${{ github.ref_name }}

